/**
 * Human-readable descriptions for every permission code.
 *
 * Shared by the role editor screens (CreateRolePage / RoleDetailPage) so the
 * copy stays consistent and only needs maintaining in one place.
  *
 * One permission = one action: every subsection's create / edit / delete /
 * approve / reject is its own code.
 *
 * Keys mirror the permission catalogue seeded in
 * HRMS-backend/apps/permissions/migrations/.
 */
export const PERMISSION_DESCRIPTIONS: Record<string, string> = {
  // ─── Overview ──────────────────────────────────────────────────────────────
  'dashboard.view': 'Access the main dashboard with charts and metrics',

  // ─── People ────────────────────────────────────────────────────────────────
  'employees.view': 'Access the employee directory, view profiles and employee details',
  'employees.create': 'Add new employees and fill in their profile information',
  'employees.edit': 'Update employee personal details, job info and profile data',
  'employees.delete': 'Permanently remove employee records from the system',

  'departments.view': 'View the list of departments',
  'departments.create': 'Create new departments',
  'departments.edit': 'Edit existing departments',
  'departments.delete': 'Delete departments',
  'designations.view': 'View the list of designations',
  'designations.create': 'Create new designations',
  'designations.edit': 'Edit existing designations',
  'designations.delete': 'Delete designations',
  'employee_grades.view': 'View employee grades',
  'employee_grades.create': 'Create new employee grades',
  'employee_grades.edit': 'Edit existing employee grades',
  'employee_grades.delete': 'Delete employee grades',
  'department_approvers.view': 'View which approver is configured for each department',
  'department_approvers.create': 'Assign a department approver',
  'department_approvers.edit': 'Change a department approver',
  'department_approvers.delete': 'Remove a department approver',
  'branches.view': 'View branches and locations',
  'branches.create': 'Create new branches',
  'branches.edit': 'Edit existing branches',
  'branches.delete': 'Delete branches',

  'transfers.view': 'View employee transfer records',
  'transfers.create': 'Raise a new employee transfer request',
  'transfers.edit': 'Edit existing transfer records',
  'transfers.delete': 'Delete transfer records',
  'transfers.approve': 'Show the Approve button and approve employee transfers',
  'transfers.reject': 'Show the Reject button and reject employee transfers',

  'promotions.view': 'View employee promotion records',
  'promotions.create': 'Raise a new employee promotion',
  'promotions.edit': 'Edit existing promotion records',
  'promotions.delete': 'Delete promotion records',
  'promotions.approve': 'Show the Approve button and approve employee promotions',
  'promotions.reject': 'Show the Reject button and reject employee promotions',

  // ─── Leaves ────────────────────────────────────────────────────────────────
  'leaves.view': 'Access My Leaves to see personal balances, history and status',
  'leaves.create': 'Submit leave applications',
  'leave_approvals.view': 'Access the Leave Approvals page and see pending applications',
  'leaves.approve': 'Show the Approve button and approve leave applications',
  'leaves.reject': 'Show the Reject button and reject leave applications',

  'leave_policies.view': 'View leave policies',
  'leave_policies.create': 'Create leave policies',
  'leave_policies.edit': 'Edit leave policies',
  'leave_policies.delete': 'Delete leave policies',
  'leave_policy_assignments.view': 'View which leave policy is assigned to whom',
  'leave_policy_assignments.create': 'Assign leave policies',
  'leave_policy_assignments.edit': 'Edit leave policy assignments',
  'leave_policy_assignments.delete': 'Remove leave policy assignments',
  'leave_block_lists.view': 'View leave block lists (dates when leave cannot be taken)',
  'leave_block_lists.create': 'Create leave block lists',
  'leave_block_lists.edit': 'Edit leave block lists',
  'leave_block_lists.delete': 'Delete leave block lists',
  'leave_adjustments.view': 'View manual leave balance adjustments',
  'leave_adjustments.create': 'Create leave balance adjustments',
  'leave_adjustments.edit': 'Edit leave balance adjustments',
  'leave_adjustments.delete': 'Delete leave balance adjustments',
  'earned_leave_schedules.view': 'View earned leave accrual schedules',
  'earned_leave_schedules.create': 'Create earned leave schedules',
  'earned_leave_schedules.edit': 'Edit earned leave schedules',
  'earned_leave_schedules.delete': 'Delete earned leave schedules',
  'loss_of_pay.view': 'View loss of pay policies and balances',
  'loss_of_pay.create': 'Create loss of pay policies',
  'loss_of_pay.edit': 'Edit loss of pay policies',
  'loss_of_pay.delete': 'Delete loss of pay policies',

  // ─── Attendance ────────────────────────────────────────────────────────────
  'attendance.view': 'View attendance records and check in/out',
  'attendance.create': 'Manually create attendance entries for employees',
  'attendance.edit': 'Edit existing attendance records',
  'attendance.delete': 'Delete attendance records',

  'my_attendance.view': 'Access My Attendance to view own attendance history by month',
  'attendance_register.view': 'View the consolidated monthly attendance register',
  'attendance_register.create': 'Add entries to the attendance register',
  'attendance_register.edit': 'Amend entries in the attendance register',
  'attendance_register.delete': 'Remove entries from the attendance register',

  'attendance_requests.view': 'View attendance correction requests',
  'attendance_requests.create': 'Raise an attendance correction request',
  'attendance_requests.approve': 'Show the Approve button and approve attendance correction requests',
  'attendance_requests.reject': 'Show the Reject button and reject attendance correction requests',

  'attendance_upload.manage': 'Bulk upload attendance data from a CSV file',
  'geofence_locations.view': 'View configured geo-fence locations',
  'geofence_locations.create': 'Create geo-fence locations',
  'geofence_locations.edit': 'Edit geo-fence locations',
  'geofence_locations.delete': 'Delete geo-fence locations',

  'shifts.view': 'View shifts and personal shift schedule',
  'shifts.create': 'Create manual shift assignments',
  'shifts.edit': 'Edit shift assignments',
  'shifts.delete': 'Delete shift assignments',
  'shift_types.view': 'View shift type definitions',
  'shift_types.create': 'Create shift types',
  'shift_types.edit': 'Edit shift types',
  'shift_types.delete': 'Delete shift types',
  'shift_requests.view': 'View shift change requests',
  'shift_requests.create': 'Raise a shift change request',
  'shift_requests.approve': 'Show the Approve button and approve shift change requests',
  'shift_requests.reject': 'Show the Reject button and reject shift change requests',
  'shift_schedules.view': 'View shift schedules and rosters',
  'shift_schedules.create': 'Create shift schedules',
  'shift_schedules.edit': 'Edit shift schedules',
  'shift_schedules.delete': 'Delete shift schedules',

  // ─── Payroll ───────────────────────────────────────────────────────────────
  'payroll_runs.view': 'Access the Payroll Runs page and view run status',
  'payroll.create': 'Create and generate new payroll runs',
  'payroll.edit': 'Edit payroll runs before processing',
  'payroll.delete': 'Delete payroll runs',
  'payroll.submit': 'Submit a payroll run for approval',
  'payroll.disburse': 'Mark a payroll run as disbursed',
  'payroll.view': 'View salary slips and compensation data',

  'salary_components.view': 'View salary components (earnings and deductions)',
  'salary_components.create': 'Create salary components',
  'salary_components.edit': 'Edit salary components',
  'salary_components.delete': 'Delete salary components',
  'salary_structures.view': 'View salary structures',
  'salary_structures.create': 'Create salary structures',
  'salary_structures.edit': 'Edit salary structures',
  'salary_structures.delete': 'Delete salary structures',
  'salary_structure_assignments.view': 'View which salary structure is assigned to whom',
  'salary_structure_assignments.create': 'Assign salary structures',
  'salary_structure_assignments.edit': 'Edit structure assignments',
  'salary_structure_assignments.delete': 'Remove structure assignments',
  'payroll_periods.view': 'View payroll periods',
  'payroll_periods.create': 'Create payroll periods',
  'payroll_periods.edit': 'Edit payroll periods',
  'payroll_periods.delete': 'Delete payroll periods',
  'payroll_corrections.view': 'View payroll corrections',
  'payroll_corrections.create': 'Create payroll corrections',
  'payroll_corrections.edit': 'Edit payroll corrections',
  'payroll_corrections.delete': 'Delete payroll corrections',
  'employee_incentives.view': 'View employee incentives and bonuses',
  'employee_incentives.create': 'Create employee incentives',
  'employee_incentives.edit': 'Edit employee incentives',
  'employee_incentives.delete': 'Delete employee incentives',
  'gratuity.view': 'View gratuity records and calculations',
  'gratuity.create': 'Create gratuity records',
  'gratuity.edit': 'Edit gratuity records',
  'gratuity.delete': 'Delete gratuity records',

  // ─── Recruitment ───────────────────────────────────────────────────────────
  'job_openings.view': 'View job openings',
  'job_openings.create': 'Create job openings',
  'job_openings.edit': 'Edit / publish / close job openings',
  'job_openings.delete': 'Delete job openings',
  'recruitment.view': 'View candidates and the hiring pipeline',
  'recruitment.create': 'Add candidates and schedule interviews',
  'recruitment.edit': 'Move candidates through pipeline stages and edit their details',
  'recruitment.delete': 'Delete candidates and cancel interviews',
  'referrals.view': 'View employee referrals',
  'referrals.create': 'Create referrals',
  'referrals.edit': 'Edit referrals',
  'referrals.delete': 'Delete referrals',
  'interview_types.view': 'View interview type definitions',
  'interview_types.create': 'Create interview types',
  'interview_types.edit': 'Edit interview types',
  'interview_types.delete': 'Delete interview types',
  'job_templates.view': 'View reusable job description templates',
  'job_templates.create': 'Create job templates',
  'job_templates.edit': 'Edit job templates',
  'job_templates.delete': 'Delete job templates',

  // ─── Performance ───────────────────────────────────────────────────────────
  'appraisals.view': 'View appraisal cycles and individual appraisals',
  'appraisals.create': 'Create appraisal cycles and appraisals',
  'appraisals.edit': 'Edit appraisal records and ratings',
  'appraisals.delete': 'Delete appraisal records',
  'appraisals.approve': 'Show the Approve button and approve submitted appraisals',
  'appraisals.reject': 'Show the Reject button and reject submitted appraisals',
  'kras.view': 'View Key Result Areas',
  'kras.create': 'Create KRAs',
  'kras.edit': 'Edit KRAs',
  'kras.delete': 'Delete KRAs',
  'appraisal_templates.view': 'View appraisal templates',
  'appraisal_templates.create': 'Create appraisal templates',
  'appraisal_templates.edit': 'Edit appraisal templates',
  'appraisal_templates.delete': 'Delete appraisal templates',
  'goals.view': 'View employee goals',
  'goals.create': 'Create goals',
  'goals.edit': 'Edit goals',
  'goals.delete': 'Delete goals',
  'performance_feedback.view': 'View performance feedback',
  'performance_feedback.create': 'Give performance feedback',
  'performance_feedback.edit': 'Edit performance feedback',
  'performance_feedback.delete': 'Delete performance feedback',

  // ─── Expenses ──────────────────────────────────────────────────────────────
  'expenses.view': 'View own expense claims and reimbursement history',
  'expenses.create': 'Submit new expense claims with receipts',
  'expenses.edit': 'Modify expense claim details',
  'expenses.delete': 'Delete expense claims',
  'expense_approvals.view': 'Access the Expense Approvals page and see pending claims',
  'expenses.approve': 'Show the Approve button and approve expense claims',
  'expenses.reject': 'Show the Reject button and reject expense claims',
  'expenses.mark_paid': 'Mark approved expense claims as paid/reimbursed',
  'expense_advances.view': 'View employee advance requests',
  'expense_advances.create': 'Request an employee advance',
  'expense_advances.approve': 'Show the Approve button and approve employee advances',
  'expense_advances.reject': 'Show the Reject button and reject employee advances',
  'expense_types.view': 'View expense types/categories',
  'expense_types.create': 'Create expense types',
  'expense_types.edit': 'Edit expense types',
  'expense_types.delete': 'Delete expense types',
  'expense_taxes.view': 'View expense tax configuration',
  'expense_taxes.create': 'Create expense taxes',
  'expense_taxes.edit': 'Edit expense taxes',
  'expense_taxes.delete': 'Delete expense taxes',

  // ─── Learning ──────────────────────────────────────────────────────────────
  'onboarding.view': 'View onboarding checklists and new hire tasks',
  'onboarding.create': 'Create onboarding plans for new employees',
  'onboarding.edit': 'Edit onboarding tasks and checklists',
  'onboarding.delete': 'Delete onboarding records',
  'onboarding_templates.view': 'View onboarding templates',
  'onboarding_templates.create': 'Create onboarding templates',
  'onboarding_templates.edit': 'Edit onboarding templates',
  'onboarding_templates.delete': 'Delete onboarding templates',
  'onboarding_tracking.view': 'View the onboarding tracking dashboard',
  'onboarding_tracking.create': 'Assign onboarding tasks',
  'onboarding_tracking.edit': 'Reassign / update onboarding tasks',
  'onboarding_tracking.delete': 'Remove onboarding task assignments',
  'training.view': 'View training events, schedules and enrolments',
  'training.create': 'Create training sessions and enrol employees',
  'training.edit': 'Edit training event details',
  'training.delete': 'Delete training records',
  'training_programs.view': 'View training programs',
  'training_programs.create': 'Create training programs',
  'training_programs.edit': 'Edit training programs',
  'training_programs.delete': 'Delete training programs',
  'training_results.view': 'View training results and scores',
  'training_results.create': 'Record training results',
  'training_results.edit': 'Edit training results',
  'training_results.delete': 'Delete training results',

  // ─── More ──────────────────────────────────────────────────────────────────
  'grievances.view': 'View submitted grievance tickets',
  'grievances.create': 'Submit new grievance complaints',
  'grievances.edit': 'Update grievance status and details',
  'grievances.delete': 'Delete grievance records',
  'grievances.approve': 'Show the Resolve action and resolve grievances',
  'grievances.reject': 'Show the Reject/Close action and reject or close grievances',
  'grievance_types.view': 'View grievance types',
  'grievance_types.create': 'Create grievance types',
  'grievance_types.edit': 'Edit grievance types',
  'grievance_types.delete': 'Delete grievance types',

  'travel.view': 'View travel requests and itineraries',
  'travel.create': 'Submit travel requests with trip details',
  'travel.edit': 'Modify travel request information',
  'travel.delete': 'Delete travel records',
  'travel.approve': 'Show the Approve button and approve travel requests',
  'travel.reject': 'Show the Reject button and reject travel requests',

  'overtime.view': 'View overtime slips and hours worked',
  'overtime.create': 'Log overtime hours',
  'overtime.edit': 'Edit overtime entries',
  'overtime.delete': 'Delete overtime records',
  'overtime.approve': 'Show the Approve button and approve overtime claims',
  'overtime.reject': 'Show the Reject button and reject overtime claims',
  'overtime_types.view': 'View overtime types',
  'overtime_types.create': 'Create overtime types',
  'overtime_types.edit': 'Edit overtime types',
  'overtime_types.delete': 'Delete overtime types',

  'settlements.view': 'View full & final settlement records',
  'settlements.create': 'Initiate the settlement process for exiting employees',
  'settlements.edit': 'Modify settlement calculations and details',
  'settlements.delete': 'Delete settlement records',
  'settlements.approve': 'Show the Approve button and approve settlements',
  'settlements.reject': 'Show the Reject button and reject settlements',
  'settlements.mark_paid': 'Mark an approved settlement as paid/disbursed',

  'exit_interviews.view': 'View exit interview records for departing employees',
  'exit_interviews.create': 'Create exit interview records',
  'exit_interviews.edit': 'Edit exit interview records',
  'exit_interviews.delete': 'Delete exit interview records',
  'holiday_assignments.view': 'View holiday list assignments',
  'holiday_assignments.create': 'Assign holiday lists to employees and departments',
  'holiday_assignments.edit': 'Edit holiday list assignments',
  'holiday_assignments.delete': 'Remove holiday list assignments',
  'holidays.view': 'View holiday lists and their entries',
  'holidays.create': 'Create holiday lists and entries',
  'holidays.edit': 'Edit holiday lists and entries',
  'holidays.delete': 'Delete holiday lists and entries',
  'health_insurance.view': 'View employee health insurance records',
  'health_insurance.create': 'Create health insurance records',
  'health_insurance.edit': 'Edit health insurance records',
  'health_insurance.delete': 'Delete health insurance records',
  'cost_centers.view': 'View employee cost center assignments',
  'cost_centers.create': 'Create cost center allocations',
  'cost_centers.edit': 'Edit cost center allocations',
  'cost_centers.delete': 'Delete cost center allocations',
  'document_types.view': 'View document type definitions',
  'document_types.create': 'Create document types',
  'document_types.edit': 'Edit document types',
  'document_types.delete': 'Delete document types',
  'documents.view': 'View employee uploaded documents',
  'documents.create': 'Upload employee documents',
  'documents.edit': 'Edit employee documents',
  'documents.delete': 'Delete employee documents',
  'appointment_letters.view': 'View appointment letter templates',
  'appointment_letters.create': 'Create appointment letter templates',
  'appointment_letters.edit': 'Edit appointment letter templates',
  'appointment_letters.delete': 'Delete appointment letter templates',

  // ─── Admin ─────────────────────────────────────────────────────────────────
  'permissions.view': 'View the list of all available permissions in the system',
  'roles.manage': 'Create, edit and delete roles and assign permissions to them',
  'hr_settings.view': 'View HR settings',
  'hr_settings.manage': 'Change organisation-wide HR settings',
  'audit_logs.view': 'View the audit log of system activity',
};
